@Host = https://usmpsunat.herokuapp.com/
GET {{Host}}/facturas HTTP/1.1
Accept: application/json

GET {{Host}}/factura/1 HTTP/1.1
Accept: application/json

POST {{Host}}/factura HTTP/1.1
Content-Type: application/json

{
    "descrip" : "hola 5",
    "razonSoc" : "Test4",
    "montoIGV" : 2000

}

PUT {{Host}}/factura HTTP/1.1
Content-Type: application/json

{
    "id" : 1,
    "descrip" : "Test4",
    "razonSoc" : "Test4",
    "montoIGV" : 2000

}